version: '3'
services:
  app:
    build: .
    container_name: urlshortener_app
    ports:
      - "1323:1323"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Amineyk85
      DB_NAME: urlshortener
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: amin
    networks:
      - backend

  db:
    image: postgres:16
    volumes:
      - /data/postgres:/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Amineyk85
        POSTGRES_DB: urlshortener
    networks:
        - backend
  redis:
    image: redis:7.0.15
    volumes:
      - /data/redis:/data
    command: redis-server --requirepass "amin"
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: amin
    networks:
        - backend
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - backend

  grafana:
      image: grafana/grafana
      container_name: grafana
      ports:
        - "3000:3000"
      depends_on:
        - prometheus
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      volumes:
        - grafana_data:/var/lib/grafana
      networks:
        - backend
        
networks:
    backend:

volumes:
    grafana_data: